#!/bin/sh
set -e

if ls /root/.ssh/host_keys/ssh_host_* 1> /dev/null 2>&1; then
    cp /root/.ssh/host_keys/ssh_host_* /etc/ssh
fi

if ! ls /etc/ssh/ssh_host_* 1> /dev/null 2>&1; then
    ssh-keygen -A
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- sshd "$@"
fi

chown root:root /root/.ssh/authorized_keys
chmod 600 /root/.ssh/authorized_keys

passwd -d -u root || true

exec "$@"